// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/payments": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "List payment queue",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/scheduler.PaymentEvent"
                            }
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/payments/process": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Process pending payments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ProcessPaymentsResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/pull": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workers"
                ],
                "summary": "Pull next assignment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Worker ID",
                        "name": "worker_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scheduler.Assignment"
                        }
                    },
                    "204": {
                        "description": "No assignment",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/result": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Submit job result",
                "parameters": [
                    {
                        "description": "Result payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scheduler.ResultSubmission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scheduler.Decision"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Scheduler stats snapshot",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scheduler.Stats"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/workers/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workers"
                ],
                "summary": "Register worker or heartbeat",
                "parameters": [
                    {
                        "description": "Worker register request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.RegisterWorkerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scheduler.Worker"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ProcessPaymentsResponse": {
            "type": "object",
            "properties": {
                "processed_count": {
                    "type": "integer"
                }
            }
        },
        "main.RegisterWorkerRequest": {
            "type": "object",
            "properties": {
                "worker_id": {
                    "type": "string"
                }
            }
        },
        "scheduler.Assignment": {
            "type": "object",
            "properties": {
                "args": {
                    "type": "array",
                    "items": {}
                },
                "job_id": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "required_rep": {
                    "type": "integer"
                },
                "reward_usdc": {
                    "type": "string"
                },
                "wasm_url": {
                    "type": "string"
                },
                "workflow_id": {
                    "type": "string"
                }
            }
        },
        "scheduler.Decision": {
            "type": "object",
            "properties": {
                "accepted_payload": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "accepted_result": {
                    "type": "string"
                },
                "accepted_workers": {
                    "type": "integer"
                },
                "finalized": {
                    "type": "boolean"
                },
                "job_id": {
                    "type": "string"
                },
                "required_replicas": {
                    "type": "integer"
                }
            }
        },
        "scheduler.PaymentEvent": {
            "type": "object",
            "properties": {
                "accepted_hash": {
                    "type": "string"
                },
                "amount_usdc": {
                    "type": "string"
                },
                "attempts": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "last_error": {
                    "type": "string"
                },
                "network": {
                    "type": "string"
                },
                "payer": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "worker_id": {
                    "type": "string"
                },
                "workflow_id": {
                    "type": "string"
                }
            }
        },
        "scheduler.ResultSubmission": {
            "type": "object",
            "properties": {
                "job_id": {
                    "type": "string"
                },
                "result_payload": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "result_sig": {
                    "type": "string"
                },
                "worker_id": {
                    "type": "string"
                }
            }
        },
        "scheduler.Stats": {
            "type": "object",
            "properties": {
                "finalized_jobs": {
                    "type": "integer"
                },
                "pending_payments": {
                    "type": "integer"
                },
                "queued_jobs": {
                    "type": "integer"
                },
                "total_jobs": {
                    "type": "integer"
                },
                "workers_online": {
                    "type": "integer"
                }
            }
        },
        "scheduler.Worker": {
            "type": "object",
            "properties": {
                "connected_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_heartbeat": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "x402 Scheduler API",
	Description:      "Worker registration, job pull, result submit, payments, stats.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
